name: 'Build and push image'
on:
  push:
    tags:
      - v*.*.*

env:
  IMAGE_NAME: 'glitchcrab/jenkins-docker'

jobs:
  plan:
    name: 'Build and push'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=RELEASE_TAG::${GITHUB_REF/refs\/tags\//}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.RELEASE_TAG }}
            ${{ env.IMAGE_NAME }}:latest
