name: 'Create release'
on:
  push:
    tags:
      - v*.*.*

jobs:
  plan:
    name: 'Create release'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Automated release for tag ${{ github.ref }}
          draft: false
          prerelease: false
