name: 'Build and push image'
on:
  pull_request:

env:
  IMAGE_NAME: 'glitchcrab/jenkins-docker'

jobs:
  plan:
    name: 'Build and push'
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Pull image
        run: docker pull ${{ env.IMAGE_NAME }}:latest
